spring:
  application:
    name: spring-boot-learning
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/localhost?useTimeZone=true&serverTimeZone=UTC
    username: root
    password: vebas123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false